### ISSUE TITLE
Navigation between Batch Jams

### ISSUE THREAD

**Issue by karmanyaahm** [hackclub/jams#136]
Like at the end of Part 1, it would be nice to have a "Next Jam" button that takes you straight to part 2.

**Comment by karmanyaahm** [comment]
![image](https://github.com/hackclub/jams/assets/32671690/e05fdd1e-3e40-4ed9-833b-f82b2e1bc2aa)
Just like there's previous here but on the bottom.

**Comment by thesuperRL** [comment]
This issue only exists for the USB hub jam, as the creator did not add a required parameter for batch jams, "totalParts". This makes it so that the program doesn't know if this is the last part or not, thus not having a next button. I just added this parameter to the jam in #140, it should be fixed now.
